#  Step 2  EDA


In [92]:
!python --version


Python 3.10.5


In [93]:
import pandas as pd
import numpy as np


In [94]:
car_df = pd.read_csv('Car_Insurance_Claim.csv')
car_df

ID    AGE  GENDER      RACE DRIVING_EXPERIENCE    EDUCATION  \
0     569520    65+  female  majority               0-9y  high school   
1     750365  16-25    male  majority               0-9y         none   
2     199901  16-25  female  majority               0-9y  high school   
3     478866  16-25    male  majority               0-9y   university   
4     731664  26-39    male  majority             10-19y         none   
...      ...    ...     ...       ...                ...          ...   
9995  323164  26-39  female  majority             10-19y   university   
9996  910346  26-39  female  majority             10-19y         none   
9997  468409  26-39    male  majority               0-9y  high school   
9998  903459  26-39  female  majority             10-19y  high school   
9999  442696  26-39  female  majority               0-9y         none   

             INCOME  CREDIT_SCORE  VEHICLE_OWNERSHIP VEHICLE_YEAR  MARRIED  \
0       upper class      0.629027                1.0   after 2015      0.0   
1           poverty      0.357757                0.0  before 2015      0.0   
2     working class      0.493146                1.0  before 2015      0.0   
3     working class      0.206013                1.0  before 2015      0.0   
4     working class      0.388366                1.0  before 2015      0.0   
...             ...           ...                ...          ...      ...   
9995    upper class      0.582787                1.0  before 2015      0.0   
9996   middle class      0.522231                1.0   after 2015      0.0   
9997   middle class      0.470940                1.0  before 2015      0.0   
9998        poverty      0.364185                0.0  before 2015      0.0   
9999  working class      0.435225                1.0  before 2015      1.0   

      CHILDREN  POSTAL_CODE  ANNUAL_MILEAGE VEHICLE_TYPE  SPEEDING_VIOLATIONS  \
0          1.0        10238         12000.0        sedan                    0   
1          0.0        10238         16000.0        sedan                    0   
2          0.0        10238         11000.0        sedan                    0   
3          1.0        32765         11000.0        sedan                    0   
4          0.0        32765         12000.0        sedan                    2   
...        ...          ...             ...          ...                  ...   
9995       0.0        10238         16000.0        sedan                    0   
9996       1.0        32765             NaN        sedan                    1   
9997       1.0        10238         14000.0        sedan                    0   
9998       1.0        10238         13000.0        sedan                    2   
9999       1.0        10238         13000.0        sedan                    0   

      DUIS  PAST_ACCIDENTS  OUTCOME  
0        0               0      0.0  
1        0               0      1.0  
2        0               0      0.0  
3        0               0      0.0  
4        0               1      1.0  
...    ...             ...      ...  
9995     0               1      0.0  
9996     0               0      0.0  
9997     0               0      0.0  
9998     0               1      1.0  
9999     0               0      0.0  

[10000 rows x 19 columns]

In [95]:
car_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   ID                   10000 non-null  int64  
 1   AGE                  10000 non-null  object 
 2   GENDER               10000 non-null  object 
 3   RACE                 10000 non-null  object 
 4   DRIVING_EXPERIENCE   10000 non-null  object 
 5   EDUCATION            10000 non-null  object 
 6   INCOME               10000 non-null  object 
 7   CREDIT_SCORE         9018 non-null   float64
 8   VEHICLE_OWNERSHIP    10000 non-null  float64
 9   VEHICLE_YEAR         10000 non-null  object 
 10  MARRIED              10000 non-null  float64
 11  CHILDREN             10000 non-null  float64
 12  POSTAL_CODE          10000 non-null  int64  
 13  ANNUAL_MILEAGE       9043 non-null   float64
 14  VEHICLE_TYPE         10000 non-null  object 
 15  SPEEDING_VIOLATIONS  10000 non-null  

In [96]:
car_df.describe()

ID  CREDIT_SCORE  VEHICLE_OWNERSHIP       MARRIED  \
count   10000.000000   9018.000000       10000.000000  10000.000000   
mean   500521.906800      0.515813           0.697000      0.498200   
std    290030.768758      0.137688           0.459578      0.500022   
min       101.000000      0.053358           0.000000      0.000000   
25%    249638.500000      0.417191           0.000000      0.000000   
50%    501777.000000      0.525033           1.000000      0.000000   
75%    753974.500000      0.618312           1.000000      1.000000   
max    999976.000000      0.960819           1.000000      1.000000   

           CHILDREN   POSTAL_CODE  ANNUAL_MILEAGE  SPEEDING_VIOLATIONS  \
count  10000.000000  10000.000000     9043.000000         10000.000000   
mean       0.688800  19864.548400    11697.003207             1.482900   
std        0.463008  18915.613855     2818.434528             2.241966   
min        0.000000  10238.000000     2000.000000             0.000000   
25%        0.000000  10238.000000    10000.000000             0.000000   
50%        1.000000  10238.000000    12000.000000             0.000000   
75%        1.000000  32765.000000    14000.000000             2.000000   
max        1.000000  92101.000000    22000.000000            22.000000   

              DUIS  PAST_ACCIDENTS       OUTCOME  
count  10000.00000    10000.000000  10000.000000  
mean       0.23920        1.056300      0.313300  
std        0.55499        1.652454      0.463858  
min        0.00000        0.000000      0.000000  
25%        0.00000        0.000000      0.000000  
50%        0.00000        0.000000      0.000000  
75%        0.00000        2.000000      1.000000  
max        6.00000       15.000000      1.000000

In [97]:
car_df['CREDIT_SCORE']= car_df['CREDIT_SCORE'].fillna(car_df['CREDIT_SCORE'].mean())

In [98]:
car_df['ANNUAL_MILEAGE'].isnull().sum()/len(car_df['ANNUAL_MILEAGE'])*100

9.569999999999999

In [99]:
car_df['ANNUAL_MILEAGE'].mode()

0    11000.0
Name: ANNUAL_MILEAGE, dtype: float64

In [100]:
car_df['ANNUAL_MILEAGE'].fillna(11000.0,inplace=True)

In [101]:
car_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   ID                   10000 non-null  int64  
 1   AGE                  10000 non-null  object 
 2   GENDER               10000 non-null  object 
 3   RACE                 10000 non-null  object 
 4   DRIVING_EXPERIENCE   10000 non-null  object 
 5   EDUCATION            10000 non-null  object 
 6   INCOME               10000 non-null  object 
 7   CREDIT_SCORE         10000 non-null  float64
 8   VEHICLE_OWNERSHIP    10000 non-null  float64
 9   VEHICLE_YEAR         10000 non-null  object 
 10  MARRIED              10000 non-null  float64
 11  CHILDREN             10000 non-null  float64
 12  POSTAL_CODE          10000 non-null  int64  
 13  ANNUAL_MILEAGE       10000 non-null  float64
 14  VEHICLE_TYPE         10000 non-null  object 
 15  SPEEDING_VIOLATIONS  10000 non-null  

In [102]:
car_df['AGE'].unique()

array(['65+', '16-25', '26-39', '40-64'], dtype=object)

In [103]:
from sklearn.preprocessing import LabelEncoder

In [104]:
le = LabelEncoder()

car_df['AGE']= le.fit_transform(car_df['AGE'])

In [105]:
car_df['AGE'].unique()

array([3, 0, 1, 2])

In [106]:
car_df['GENDER'].unique()

array(['female', 'male'], dtype=object)

In [107]:
car_df['GENDER'].replace({'female':0,'male':1},inplace=True)

In [108]:
car_df['GENDER'].head()

0    0
1    1
2    0
3    1
4    1
Name: GENDER, dtype: int64

In [109]:
car_df['RACE'].unique()

array(['majority', 'minority'], dtype=object)

In [110]:
car_df['RACE'].replace({'minority':0,'majority':1},inplace=True)

In [111]:
car_df['RACE'].head()

0    1
1    1
2    1
3    1
4    1
Name: RACE, dtype: int64

In [112]:
car_df['DRIVING_EXPERIENCE'].unique()

array(['0-9y', '10-19y', '20-29y', '30y+'], dtype=object)

In [113]:
car_df['DRIVING_EXPERIENCE'].unique()

array(['0-9y', '10-19y', '20-29y', '30y+'], dtype=object)

In [114]:
car_df['DRIVING_EXPERIENCE']=le.fit_transform(car_df['DRIVING_EXPERIENCE'])

In [115]:
car_df['DRIVING_EXPERIENCE'].unique()

array([0, 1, 2, 3])

In [116]:
car_df['EDUCATION'].unique()

array(['high school', 'none', 'university'], dtype=object)

In [117]:
car_df['EDUCATION'].value_counts()

high school    4157
university     3928
none           1915
Name: EDUCATION, dtype: int64

In [118]:
car_df['EDUCATION'].replace({'none':0,'high school':1,'university':2},inplace=True)

In [119]:
car_df['INCOME'].unique()

array(['upper class', 'poverty', 'working class', 'middle class'],
      dtype=object)

In [120]:
car_df['INCOME'].replace({'poverty':0,'middle class':1,'working class':2,'upper class':3},inplace=True)

In [121]:
car_df['VEHICLE_YEAR'].unique()

array(['after 2015', 'before 2015'], dtype=object)

In [122]:
car_df['VEHICLE_YEAR'].replace({'before 2015':0,'after 2015':1},inplace=True)

In [123]:
car_df['POSTAL_CODE'].unique()

array([10238, 32765, 92101, 21217], dtype=int64)

In [124]:
car_df['POSTAL_CODE']=le.fit_transform(car_df['POSTAL_CODE'])

In [125]:
car_df['VEHICLE_TYPE'].unique()

array(['sedan', 'sports car'], dtype=object)

In [126]:
car_df['VEHICLE_TYPE'].replace({'sedan':0,'sports car':1},inplace=True)

In [127]:
car_df['SPEEDING_VIOLATIONS'].unique()

array([ 0,  2,  3,  7,  6,  4, 10, 13,  1,  5,  9,  8, 12, 11, 15, 17, 19,
       18, 16, 14, 22], dtype=int64)

In [128]:
car_df['DUIS'].unique()

array([0, 2, 1, 3, 4, 5, 6], dtype=int64)

In [129]:
car_df['PAST_ACCIDENTS'].unique()

array([ 0,  1,  3,  7,  2,  5,  4,  6,  8, 10, 11,  9, 12, 14, 15],
      dtype=int64)

In [130]:
car_df['OUTCOME'].head()

0    0.0
1    1.0
2    0.0
3    0.0
4    1.0
Name: OUTCOME, dtype: float64

In [131]:
import seaborn as sns
import matplotlib.pyplot as plt

In [132]:
car_df.columns

Index(['ID', 'AGE', 'GENDER', 'RACE', 'DRIVING_EXPERIENCE', 'EDUCATION',
       'INCOME', 'CREDIT_SCORE', 'VEHICLE_OWNERSHIP', 'VEHICLE_YEAR',
       'MARRIED', 'CHILDREN', 'POSTAL_CODE', 'ANNUAL_MILEAGE', 'VEHICLE_TYPE',
       'SPEEDING_VIOLATIONS', 'DUIS', 'PAST_ACCIDENTS', 'OUTCOME'],
      dtype='object')

# Feature Sellection

In [133]:
from sklearn.model_selection import train_test_split

In [134]:
x=car_df.drop(columns=['ID','OUTCOME','MARRIED','CHILDREN','EDUCATION'])
y=car_df["OUTCOME"]

In [135]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=45,stratify=y)

In [136]:
x_train

AGE  GENDER  RACE  DRIVING_EXPERIENCE  INCOME  CREDIT_SCORE  \
5671    2       0     1                   2       3      0.635655   
2718    3       0     1                   3       2      0.260393   
3059    2       1     1                   2       3      0.562776   
3976    0       1     1                   0       0      0.525230   
7319    0       0     1                   0       1      0.552022   
...   ...     ...   ...                 ...     ...           ...   
1615    1       0     1                   1       3      0.590976   
6520    1       1     1                   0       1      0.432472   
465     0       1     1                   0       2      0.370792   
46      3       1     1                   2       3      0.625626   
3522    3       0     1                   1       3      0.595936   

      VEHICLE_OWNERSHIP  VEHICLE_YEAR  POSTAL_CODE  ANNUAL_MILEAGE  \
5671                0.0             1            2          8000.0   
2718                0.0             1            0         12000.0   
3059                1.0             0            0         14000.0   
3976                1.0             0            0         12000.0   
7319                0.0             0            0         22000.0   
...                 ...           ...          ...             ...   
1615                1.0             1            0         14000.0   
6520                1.0             0            2         13000.0   
465                 0.0             0            0         13000.0   
46                  1.0             1            0          7000.0   
3522                1.0             1            2         11000.0   

      VEHICLE_TYPE  SPEEDING_VIOLATIONS  DUIS  PAST_ACCIDENTS  
5671             0                    2     0               0  
2718             0                    0     3               1  
3059             1                    3     1               0  
3976             0                    0     0               0  
7319             0                    0     0               0  
...            ...                  ...   ...             ...  
1615             0                    0     0               0  
6520             0                    0     0               0  
465              0                    0     0               0  
46               0                    7     0               5  
3522             0                    1     0               0  

[7000 rows x 14 columns]

In [137]:
y_train

5671    0.0
2718    0.0
3059    0.0
3976    1.0
7319    1.0
       ... 
1615    0.0
6520    1.0
465     1.0
46      0.0
3522    0.0
Name: OUTCOME, Length: 7000, dtype: float64

#### Model Evaluation

# 1>LOGISTIC REGRESSION

In [138]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report


lgrs = LogisticRegression()

lgrs.fit(x_train,y_train)


############ Testing Data Evaluation ################
y_pred_test = lgrs.predict(x_test)
acc = accuracy_score(y_test,y_pred_test)
print(f"Accuracy Score = {acc}")
print(classification_report(y_test,y_pred_test))
print(confusion_matrix(y_test,y_pred_test))


########### Traning Data Evaluation ###############

y_pred_train = lgrs.predict(x_train)
acc = accuracy_score(y_train,y_pred_train)
print(f"Accuracy Score = {acc}")
print(classification_report(y_train,y_pred_train))
print(confusion_matrix(y_train,y_pred_train))


Accuracy Score = 0.851
              precision    recall  f1-score   support

         0.0       0.88      0.91      0.89      2060
         1.0       0.79      0.71      0.75       940

    accuracy                           0.85      3000
   macro avg       0.83      0.81      0.82      3000
weighted avg       0.85      0.85      0.85      3000

[[1881  179]
 [ 268  672]]
Accuracy Score = 0.8434285714285714
              precision    recall  f1-score   support

         0.0       0.87      0.90      0.89      4807
         1.0       0.77      0.72      0.74      2193

    accuracy                           0.84      7000
   macro avg       0.82      0.81      0.81      7000
weighted avg       0.84      0.84      0.84      7000

[[4335  472]
 [ 624 1569]]


# Dicision Tree 

In [139]:
from sklearn.tree import DecisionTreeClassifier


dt = DecisionTreeClassifier()

dt.fit(x_train,y_train)


############ Testing Data Evaluation ################
print('testing data evaluation')
print()
y_pred_test_tree = dt.predict(x_test)
acc = accuracy_score(y_test,y_pred_test_tree)
print(f"Accuracy Score = {acc}")
print(classification_report(y_test,y_pred_test_tree))
print(confusion_matrix(y_test,y_pred_test_tree))

print('*'*50)

########### Traning Data Evaluation ###############
print('training data evaluation')
print()
y_pred_train = dt.predict(x_train)
acc = accuracy_score(y_train,y_pred_train)
print(f"Accuracy Score = {acc}")
print(classification_report(y_train,y_pred_train))
print(confusion_matrix(y_train,y_pred_train))


testing data evaluation

Accuracy Score = 0.7956666666666666
              precision    recall  f1-score   support

         0.0       0.85      0.86      0.85      2060
         1.0       0.68      0.66      0.67       940

    accuracy                           0.80      3000
   macro avg       0.76      0.76      0.76      3000
weighted avg       0.79      0.80      0.79      3000

[[1767  293]
 [ 320  620]]
**************************************************
training data evaluation

Accuracy Score = 0.999
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00      4807
         1.0       1.00      1.00      1.00      2193

    accuracy                           1.00      7000
   macro avg       1.00      1.00      1.00      7000
weighted avg       1.00      1.00      1.00      7000

[[4805    2]
 [   5 2188]]


In [140]:
from sklearn.model_selection import GridSearchCV,RandomizedSearchCV


hyp = { 'criterion' : ['gini','entropy'],
        'max_depth' : np.arange(2,10),
        'min_samples_split' : np.arange(2,5),
        'min_samples_leaf' : np.arange(2,5)
    
}
rscv_tree_clf  =  RandomizedSearchCV(dt,hyp,cv=5)
rscv_tree_clf.fit(x_train,y_train)

rscv_tree_clf.best_params_

{'min_samples_split': 4,
 'min_samples_leaf': 2,
 'max_depth': 6,
 'criterion': 'entropy'}

In [141]:
y_pred_rscv_tree_clf = rscv_tree_clf.predict(x_test)
##### Evaluation Testing 

acc = accuracy_score(y_test,y_pred_rscv_tree_clf)
print(f"Accuracy Score = {acc}")
print(classification_report(y_test,y_pred_rscv_tree_clf))
print(confusion_matrix(y_test,y_pred_rscv_tree_clf))


##### Evaluation Training 
print("################# Training ################")
y_pred_train = rscv_tree_clf.predict(x_train)

acc = accuracy_score(y_train,y_pred_train)
print(f"Accuracy Score = {acc}")
print(classification_report(y_train,y_pred_train))
print(confusion_matrix(y_train,y_pred_train))

Accuracy Score = 0.8553333333333333
              precision    recall  f1-score   support

         0.0       0.89      0.90      0.90      2060
         1.0       0.77      0.76      0.77       940

    accuracy                           0.86      3000
   macro avg       0.83      0.83      0.83      3000
weighted avg       0.85      0.86      0.85      3000

[[1851  209]
 [ 225  715]]
################# Training ################
Accuracy Score = 0.8531428571428571
              precision    recall  f1-score   support

         0.0       0.89      0.89      0.89      4807
         1.0       0.76      0.77      0.77      2193

    accuracy                           0.85      7000
   macro avg       0.83      0.83      0.83      7000
weighted avg       0.85      0.85      0.85      7000

[[4284  523]
 [ 505 1688]]


In [142]:
hyp = { 'criterion' : ['gini','entropy'],
        'max_depth' : np.arange(2,10),
        'min_samples_split' : np.arange(2,5),
        'min_samples_leaf' : np.arange(2,9)
    
}
gscv_tree_clf  =  GridSearchCV(dt,hyp,cv=5)
gscv_tree_clf.fit(x_train,y_train)

gscv_tree_clf.best_params_

{'criterion': 'entropy',
 'max_depth': 7,
 'min_samples_leaf': 6,
 'min_samples_split': 2}

In [143]:
y_pred_gscv_tree_clf = gscv_tree_clf.predict(x_test)
##### Evaluation Testing 

acc = accuracy_score(y_test,y_pred_gscv_tree_clf)
print(f"Accuracy Score = {acc}")
print(classification_report(y_test,y_pred_gscv_tree_clf))
print(confusion_matrix(y_test,y_pred_gscv_tree_clf))


##### Evaluation Training 
print("################# Training ################")
y_pred_train = gscv_tree_clf.predict(x_train)

acc = accuracy_score(y_train,y_pred_train)
print(f"Accuracy Score = {acc}")
print(classification_report(y_train,y_pred_train))
print(confusion_matrix(y_train,y_pred_train))

Accuracy Score = 0.8516666666666667
              precision    recall  f1-score   support

         0.0       0.89      0.90      0.89      2060
         1.0       0.77      0.75      0.76       940

    accuracy                           0.85      3000
   macro avg       0.83      0.82      0.83      3000
weighted avg       0.85      0.85      0.85      3000

[[1851  209]
 [ 236  704]]
################# Training ################
Accuracy Score = 0.8582857142857143
              precision    recall  f1-score   support

         0.0       0.89      0.90      0.90      4807
         1.0       0.78      0.76      0.77      2193

    accuracy                           0.86      7000
   macro avg       0.84      0.83      0.83      7000
weighted avg       0.86      0.86      0.86      7000

[[4333  474]
 [ 518 1675]]


# Random Forest

In [144]:
from sklearn.ensemble import RandomForestClassifier

rf_clf = RandomForestClassifier()
rf_clf.fit(x_train,y_train)

############ Testing Data Evaluation ################
print('testing data evaluation')
print()
y_pred_test_rf = rf_clf.predict(x_test)
acc = accuracy_score(y_test,y_pred_test_rf)
print(f"Accuracy Score = {acc}")
print(classification_report(y_test,y_pred_test_rf))
print(confusion_matrix(y_test,y_pred_test_rf))

print('*'*50)

########### Traning Data Evaluation ###############
print('training data evaluation')
print()
y_pred_train = rf_clf.predict(x_train)
acc = accuracy_score(y_train,y_pred_train)
print(f"Accuracy Score = {acc}")
print(classification_report(y_train,y_pred_train))
print(confusion_matrix(y_train,y_pred_train))


testing data evaluation

Accuracy Score = 0.8346666666666667
              precision    recall  f1-score   support

         0.0       0.86      0.91      0.88      2060
         1.0       0.77      0.67      0.72       940

    accuracy                           0.83      3000
   macro avg       0.81      0.79      0.80      3000
weighted avg       0.83      0.83      0.83      3000

[[1872  188]
 [ 308  632]]
**************************************************
training data evaluation

Accuracy Score = 0.999
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00      4807
         1.0       1.00      1.00      1.00      2193

    accuracy                           1.00      7000
   macro avg       1.00      1.00      1.00      7000
weighted avg       1.00      1.00      1.00      7000

[[4802    5]
 [   2 2191]]


In [145]:
hyp = { 'n_estimators': np.arange(10,200,10),
    'criterion' : ['gini','entropy'],
        'max_depth' : np.arange(2,20),
        'min_samples_split' : np.arange(2,5),
        'min_samples_leaf' : np.arange(2,5)
    
}
rscv_tree_clf  =  RandomizedSearchCV(rf_clf,hyp,cv=8)
rscv_tree_clf.fit(x_train,y_train)

rscv_tree_clf.best_params_

{'n_estimators': 40,
 'min_samples_split': 4,
 'min_samples_leaf': 3,
 'max_depth': 14,
 'criterion': 'entropy'}

In [146]:
y_pred_rscv_rf_clf = rscv_tree_clf.predict(x_test)
##### Evaluation Testing 

acc = accuracy_score(y_test,y_pred_rscv_rf_clf)
print(f"Accuracy Score = {acc}")
print(classification_report(y_test,y_pred_rscv_rf_clf))
print(confusion_matrix(y_test,y_pred_rscv_rf_clf))


##### Evaluation Training 
print("################# Training ################")
y_pred_train = rscv_tree_clf.predict(x_train)

acc = accuracy_score(y_train,y_pred_train)
print(f"Accuracy Score = {acc}")
print(classification_report(y_train,y_pred_train))
print(confusion_matrix(y_train,y_pred_train))

Accuracy Score = 0.846
              precision    recall  f1-score   support

         0.0       0.87      0.91      0.89      2060
         1.0       0.79      0.70      0.74       940

    accuracy                           0.85      3000
   macro avg       0.83      0.81      0.82      3000
weighted avg       0.84      0.85      0.84      3000

[[1882  178]
 [ 284  656]]
################# Training ################
Accuracy Score = 0.8935714285714286
              precision    recall  f1-score   support

         0.0       0.91      0.93      0.92      4807
         1.0       0.85      0.80      0.83      2193

    accuracy                           0.89      7000
   macro avg       0.88      0.87      0.87      7000
weighted avg       0.89      0.89      0.89      7000

[[4490  317]
 [ 428 1765]]


# ADABOOST CLASSIFICATION

In [147]:
from sklearn.ensemble import AdaBoostClassifier


adb_clf = AdaBoostClassifier(n_estimators=150)
adb_clf.fit(x_train,y_train)

############ Testing Data Evaluation ################
print('testing data evaluation')
print()
y_pred_test_ada = adb_clf.predict(x_test)
acc = accuracy_score(y_test,y_pred_test_ada)
print(f"Accuracy Score = {acc}")
print(classification_report(y_test,y_pred_test_ada))
print(confusion_matrix(y_test,y_pred_test_ada))

print('*'*50)

########### Traning Data Evaluation ###############
print('training data evaluation')
print()
y_pred_train = adb_clf.predict(x_train)
acc = accuracy_score(y_train,y_pred_train)
print(f"Accuracy Score = {acc}")
print(classification_report(y_train,y_pred_train))
print(confusion_matrix(y_train,y_pred_train))

testing data evaluation

Accuracy Score = 0.8473333333333334
              precision    recall  f1-score   support

         0.0       0.87      0.91      0.89      2060
         1.0       0.78      0.71      0.74       940

    accuracy                           0.85      3000
   macro avg       0.83      0.81      0.82      3000
weighted avg       0.84      0.85      0.85      3000

[[1874  186]
 [ 272  668]]
**************************************************
training data evaluation

Accuracy Score = 0.8487142857142858
              precision    recall  f1-score   support

         0.0       0.88      0.91      0.89      4807
         1.0       0.78      0.72      0.75      2193

    accuracy                           0.85      7000
   macro avg       0.83      0.81      0.82      7000
weighted avg       0.85      0.85      0.85      7000

[[4366  441]
 [ 618 1575]]


In [148]:
hyp = { 'n_estimators': np.arange(10,200,10)
    
}
rscv_ada_clf  =  RandomizedSearchCV(adb_clf,hyp,cv=8)
rscv_ada_clf.fit(x_train,y_train)

rscv_ada_clf.best_params_

{'n_estimators': 140}

In [149]:
y_pred_rscv_ada_clf = rscv_ada_clf.predict(x_test)
##### Evaluation Testing 

acc = accuracy_score(y_test,y_pred_rscv_ada_clf)
print(f"Accuracy Score = {acc}")
print(classification_report(y_test,y_pred_rscv_ada_clf))
print(confusion_matrix(y_test,y_pred_rscv_ada_clf))


##### Evaluation Training 
print("################# Training ################")
y_pred_train = rscv_tree_clf.predict(x_train)

acc = accuracy_score(y_train,y_pred_train)
print(f"Accuracy Score = {acc}")
print(classification_report(y_train,y_pred_train))
print(confusion_matrix(y_train,y_pred_train))

Accuracy Score = 0.8473333333333334
              precision    recall  f1-score   support

         0.0       0.87      0.91      0.89      2060
         1.0       0.78      0.71      0.74       940

    accuracy                           0.85      3000
   macro avg       0.83      0.81      0.82      3000
weighted avg       0.84      0.85      0.85      3000

[[1874  186]
 [ 272  668]]
################# Training ################
Accuracy Score = 0.8935714285714286
              precision    recall  f1-score   support

         0.0       0.91      0.93      0.92      4807
         1.0       0.85      0.80      0.83      2193

    accuracy                           0.89      7000
   macro avg       0.88      0.87      0.87      7000
weighted avg       0.89      0.89      0.89      7000

[[4490  317]
 [ 428 1765]]


In [150]:
from sklearn.metrics import precision_score

precision_logreg = precision_score(y_test,y_pred_test)
precision_logreg
precision_tree = precision_score(y_test, y_pred_test_tree)
precision_tree
precision_tree_hyp_rscv = precision_score(y_test,y_pred_rscv_tree_clf)
precision_tree_hyp_rscv
precision_tree_hyp_gscv = precision_score(y_test,y_pred_gscv_tree_clf)
precision_tree_hyp_gscv
precision_random_f = precision_score(y_test, y_pred_test_rf)
precision_random_f
precision_rf_hyp_rscv = precision_score(y_test,y_pred_rscv_rf_clf)
precision_rf_hyp_rscv
precision_adaboost = precision_score(y_test, y_pred_test_ada)
precision_adaboost
precision_ada_hyp_rscv = precision_score(y_test,y_pred_rscv_ada_clf)
precision_ada_hyp_rscv
print('Logestic Regression :', precision_logreg)
print('Decision Tree :',precision_tree )
print('Decision Tree hyp rscv :', precision_tree_hyp_rscv)
print('Decision Tree hyp gscv:', precision_tree_hyp_gscv)
print('Random Forest :', precision_random_f)
print('Random Forest hyp rscv :', precision_rf_hyp_rscv)
print('Adaboost  :', precision_adaboost)
print('Adaboost hyp rscv :', precision_ada_hyp_rscv)


Logestic Regression : 0.7896592244418331
Decision Tree : 0.6790799561883899
Decision Tree hyp rscv : 0.7738095238095238
Decision Tree hyp gscv: 0.7710843373493976
Random Forest : 0.7707317073170732
Random Forest hyp rscv : 0.7865707434052758
Adaboost  : 0.7822014051522248
Adaboost hyp rscv : 0.7822014051522248


In [152]:
import pickle

model = pickle.dump(lgrs,open('model1.pkl','wb'))

In [153]:
columns = x_test.columns.to_list()

In [154]:
column_dict = {'col_name':columns}

In [155]:
import json

with open ('columns_name.json','w') as file:
    json.dump(column_dict,file)

In [156]:
with open("columns_name.json","r") as json_file:
    col_name = json.load(json_file)
col_name_list =col_name['col_name']


In [157]:
len(col_name_list)

14

In [ ]:
col_name_list

['AGE',
 'GENDER',
 'RACE',
 'DRIVING_EXPERIENCE',
 'EDUCATION',
 'INCOME',
 'CREDIT_SCORE',
 'VEHICLE_OWNERSHIP',
 'VEHICLE_YEAR',
 'MARRIED',
 'CHILDREN',
 'POSTAL_CODE',
 'ANNUAL_MILEAGE',
 'VEHICLE_TYPE',
 'SPEEDING_VIOLATIONS',
 'DUIS',
 'PAST_ACCIDENTS']

In [158]:
x_test.head(10)

AGE  GENDER  RACE  DRIVING_EXPERIENCE  INCOME  CREDIT_SCORE  \
1032    0       0     1                   0       1      0.508461   
19      0       0     1                   0       2      0.417714   
962     2       0     1                   2       0      0.398031   
6766    0       0     1                   0       0      0.515813   
7724    2       1     0                   2       1      0.533485   
4702    1       1     1                   1       0      0.416662   
2381    0       1     1                   0       1      0.638242   
5491    2       0     1                   2       3      0.725626   
2434    2       0     1                   0       0      0.401299   
6160    3       1     1                   3       3      0.773160   

      VEHICLE_OWNERSHIP  VEHICLE_YEAR  POSTAL_CODE  ANNUAL_MILEAGE  \
1032                1.0             0            2         11000.0   
19                  1.0             0            0         18000.0   
962                 1.0             0            0         18000.0   
6766                0.0             0            0         15000.0   
7724                1.0             0            0          9000.0   
4702                0.0             0            0         12000.0   
2381                1.0             0            0         16000.0   
5491                1.0             1            2          5000.0   
2434                0.0             1            2          9000.0   
6160                1.0             0            2          8000.0   

      VEHICLE_TYPE  SPEEDING_VIOLATIONS  DUIS  PAST_ACCIDENTS  
1032             0                    0     0               0  
19               0                    0     0               0  
962              0                    0     0               0  
6766             0                    0     0               0  
7724             0                    6     0               2  
4702             0                    3     0               2  
2381             0                    0     0               0  
5491             0                    2     0               0  
2434             0                    0     0               0  
6160             1                   10     2               4

In [159]:
model = pickle.load(open("model1.pkl","rb"))

In [160]:
model

LogisticRegression()